name: eda
channels:
  - defaults
dependencies:
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - python=3.8
  - jupyter
  - pip:
      - wandb==0.15.4
      - pandas-profiling==2.11.0
      - pyarrow==2.0
      - Jinja2==3.0.3