name: train_random_forest
channels:
  - conda-forge
dependencies:
  - pandas=1.1.4
  - python=3.8
  - pip=20.3.3
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - matplotlib=3.2.2
  - pillow=8.1.2
  - numpy==1.22.3
  - pip:
      - wandb==0.10.21
